### ISSUE TITLE
Bulletproof design checklist

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#194]
We've discussed some amount of [new] use-cases (which for sure will be reflected in KEEP),  just as a reminder here is a checklist of what should be done to consider everything "working fine".
Issues can be fixed separately, this is just a checklist as a reminder 

- [x] **Open** polymorphism in JSON (non-sealed `Message` pattern)
- [x] Implement analogue of [kotlinx_dart_converter](https://pub.dartlang.org/packages/kotlinx_dart_converter) (see #267)
- [x] Pluggable contexts to serialize same POJO with multiple (e.g.) `Date` serializers
- [x] Ability to override format-global collection factory (`Set<Long>` -> `LongSet`)
- [x] Mechanism to provide class/file/field level serializers for non-serializable classes
- [x] Inheritance for POJO-like classes with constructor (aka non-`val` parameters)
- [x] ByteArray/patches to protobuf (`oldValue` API)
- [x] Configure-once contexts (GSON/Jackson-like)
- [x] Default values and `null` behaviour
- [x] Scoped polymorhism (not as part of the library, but PoC)
- [x] Custom enum serializers

**Comment by apomelov** [comment]
How about cycles in object graphs? It will be nice to avoid stack overflow errors and to have an ability to recover links in JS. Here is a simple but extremely valid case:
```
@Serializable
class ListElement(val value: String) {
    var prev: ListElement? = null
    var next: ListElement? = null
}

fun main(args: Array<String>) {
    val head = ListElement("head")
    val tail = ListElement("tail")

    head.next = tail
    tail.prev = head

    println(JSON.stringify(head))  // StackOverflowError occurs here
}
```
For JSON this may use relatively standard approach with json references and generate output like this:
```
{
    "value": "head",
    "prev": null,
    "next": {
        "value": "tail",
        "prev": {
            "$ref": "#"
        },
        "next": null
    }
}
```
Not sure about other formats..

**Comment by elizarov** [comment]
When you say "it is a relatively standard approach" can you point, please, to popular JSON serialization libraries that support it, so that we can check out the actual format that they use.

**Comment by apomelov** [comment]
@elizarov seems I used this one: https://www.npmjs.com/package/json-cycle
Not sure how popular is it. But as for internal protocol this approach seemed to be quite good.

**Comment by sandwwraith** [comment]
Jackson, however, does it in a different way. I also wonder how circular references can be supported in formats other than JSON.

**Comment by apomelov** [comment]
@sandwwraith just checked Jackson's approaches with managed reference or identity info. As far as I understand, it needs all the metainfo for deserialization (on the client side). That's why I was using retrocycle in my project: it gives universal approach and sends complete info in json message for all cases.
Unfortunately, can't say anything about other formats.
